---
- hosts: test
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: write the apache config file
    template: src=/etc/httpd/conf/httpd.conf dest=/etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: Firewall Settings
    firewalld: zone=public port=80/tcp permanent=true state=enabled
  - shell: firewall-cmd --reload
  handlers:
    - name: restart apache
      service: name=httpd state=restarted